
[general]
	# The action to perform when all players are sleeping
	#Allowed Values: Timelapse, SkipToDay, Nothing
	sleepAction = "SkipToDay"

[morning]
	# Reset the weather on morning (when players wake) if raining.
	morningResetWeather = true

[timelapse]
	# The action to perform on a player if they are attacked during timelapse sleep, for damage sources that do *not* match any preventions below.
	#Allowed Values: NoChange, InstantKill, Invincible
	sleepAttackedAction = "NoChange"
	# If true, damage type of 'Magic' (pre-1.19.4) or 'Indirect' (1.19.4+) will not apply to players during timelapse. This includes DoT's like Poison.
	sleepPreventMagicDamage = false
	# If true, will performance stats will be logged on timelapse end (average TPS, total time, total ticks)
	logTimelapsePerformanceStats = true
	# If true, natural spawning will be disabled during timelapse.
	# Gives a minor speed boost.
	disableNaturalSpawning = true
	# If true, LivingEntity type mobs will not travel during timelapse. Gives a minor speed boost.
	# Disabled by default since it could result in undesired loss, e.g. mobs drowning.
	# Note that this does NOT seem to include Villager movement.
	disableLivingEntityTravel = true

[bedRest]
	# Allows players to rest in a bed without sleeping, adding a 'Sleep' button next to 'Leave Bed'
	bedRestEnabled = true
	# Allows pressing Enter with no chat text to activate Sleep while resting. Requires the above bedRestEnabled to be true.
	bedRestWithChatEnter = true

