
[general]
	#Allows you to change the the internal height of Pockets
	#Range: 15 ~ 255
	internal_height = 15
	#Allows you to change the the internal height of Pockets
	#Range: 31 ~ 255
	internal_height_enhanced = 31
	#Allows you to change the the range of Dimensional Focus Jump Distance.
	#Range: 4 ~ 32
	focus_jump_range = 12
	#Whether or not blocked Structures can be used inside of a Pocket
	can_place_structures = false
	#Whether or not blocked Items can be used inside of a Pocket
	can_use_items = false
	#Whether or not blocked Commands can be used inside of a Pocket
	can_use_commands = false
	#Whether to keep the Chunks inside the Pocket Dimension Loaded
	keep_chunks_loaded = true
	#Whether the walls of Pockets can be destroyed in Creative Mode
	can_destroy_walls = false
	#Whether if reducing the Internal Height of Pocket that is larger will make it smaller
	internal_replace = false
	#Whether or not Hostile Mobs should be stopped from spawning
	stop_hostile_spawns = true
	#Whether or not the Mod will create backups on world load
	create_backups = true

[console_messages]
	#Whether this mod will print [INFO] messages to the console/log
	info = true
	#Whether this mod will print [DEBUG] messages to the console/log
	debug = false

[visual]
	#Whether or not connected textures work inside Pockets
	connected_textures_inside_pocket = true

[blocked]
	#List of Structures that are blocked when inside a Pocket
	blocked_structures = ["minecraft:bedrock", "lucky:lucky_block", "chancecubes:chance_cube", "chancecubes:chance_icosahedron", "chancecubes:giant_chance_cube", "chancecubes:cube_dispenser", "xreliquary:wraith_node"]
	#List of Items that are blocked when inside a Pocket
	blocked_items = ["minecraft:chorus_fruit", "minecraft:ender_pearl", "xreliquary:ender_staff", "inventorypets:pet_nether_portal", "inventorypets:pet_enderman", "inventorypets:pet_silverfish", "mana-and-artifice:spell", "mana-and-artifice:spell_book", "mana-and-artifice:grimoire", "notenoughwands:teleportation_wand"]
	#The required OP level when on servers to bypass the below blocked commands
	#Range: 0 ~ 4
	op_level = 4
	#List of Commands that are blocked when inside a Pocket
	blocked_commands = ["teleport", "tp", "kill", "setblock", "clone", "fill", "place", "setworldspawn", "spawnpoint", "spectate", "spreadplayers", "worldborder", "/"]

